CREATE TABLE "appointments" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"vagaro_appointment_id" text NOT NULL,
	"vagaro_data" text,
	"vagaro_customer_id" text,
	"vagaro_service_provider_id" text,
	"vagaro_service_id" text,
	"vagaro_business_id" text,
	"service_title" text NOT NULL,
	"service_category" text,
	"start_time" timestamp NOT NULL,
	"end_time" timestamp NOT NULL,
	"booking_status" text NOT NULL,
	"event_type" text,
	"amount" numeric(10, 2),
	"online_vs_inhouse" text,
	"appointment_type_code" text,
	"appointment_type_name" text,
	"booking_source" text,
	"calendar_event_id" text,
	"form_response_ids" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"last_synced_at" timestamp,
	"vagaro_created_at" timestamp,
	"vagaro_modified_at" timestamp,
	CONSTRAINT "appointments_vagaro_appointment_id_unique" UNIQUE("vagaro_appointment_id")
);
--> statement-breakpoint
CREATE TABLE "business_locations" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"vagaro_business_id" text NOT NULL,
	"vagaro_business_group_id" text,
	"vagaro_data" text,
	"business_name" text NOT NULL,
	"business_group_name" text,
	"business_alias" text,
	"business_phone" text,
	"business_email" text,
	"business_website" text,
	"vagaro_listing_url" text,
	"street_address" text,
	"city" text,
	"region_code" text,
	"region_name" text,
	"country_code" text,
	"country_name" text,
	"postal_code" text,
	"show_contact_information" boolean,
	"show_vagaro_connect" boolean,
	"service_location" text,
	"listed_on_vagaro" boolean,
	"listed_on_google" boolean,
	"listed_on_apple_maps" boolean,
	"use_employee_hours" boolean,
	"children_policy" text,
	"walk_ins_accepted" boolean,
	"payment_methods" text,
	"parking" text,
	"amenities" text,
	"online_gc_store" boolean,
	"spoken_languages" text,
	"business_hours" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"last_synced_at" timestamp,
	"vagaro_created_at" timestamp,
	"vagaro_modified_at" timestamp,
	CONSTRAINT "business_locations_vagaro_business_id_unique" UNIQUE("vagaro_business_id")
);
--> statement-breakpoint
CREATE TABLE "form_responses" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"vagaro_response_id" text NOT NULL,
	"vagaro_form_id" text NOT NULL,
	"vagaro_customer_id" text,
	"vagaro_business_id" text,
	"vagaro_appointment_id" text,
	"vagaro_membership_id" text,
	"vagaro_data" text,
	"form_title" text NOT NULL,
	"form_published_date" timestamp,
	"business_alias" text,
	"business_group_id" text,
	"questions_and_answers" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"last_synced_at" timestamp,
	CONSTRAINT "form_responses_vagaro_response_id_unique" UNIQUE("vagaro_response_id")
);
--> statement-breakpoint
CREATE TABLE "transactions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"vagaro_transaction_id" text,
	"vagaro_user_payment_id" text NOT NULL,
	"vagaro_user_payments_mst_id" text NOT NULL,
	"vagaro_customer_id" text,
	"vagaro_service_provider_id" text,
	"vagaro_business_id" text NOT NULL,
	"vagaro_appointment_id" text,
	"vagaro_data" text,
	"transaction_date" timestamp NOT NULL,
	"business_alias" text,
	"business_group_id" text,
	"brand_name" text,
	"item_sold" text NOT NULL,
	"purchase_type" text NOT NULL,
	"service_category" text,
	"quantity" integer NOT NULL,
	"cc_amount" numeric(10, 2),
	"cash_amount" numeric(10, 2),
	"check_amount" numeric(10, 2),
	"ach_amount" numeric(10, 2),
	"bank_account_amount" numeric(10, 2),
	"vagaro_pay_later_amount" numeric(10, 2),
	"other_amount" numeric(10, 2),
	"package_redemption" numeric(10, 2),
	"gc_redemption" numeric(10, 2),
	"points_amount" integer,
	"tax" numeric(10, 2),
	"tip" numeric(10, 2),
	"discount" numeric(10, 2),
	"membership_amount" numeric(10, 2),
	"product_discount" numeric(10, 2),
	"amount_due" numeric(10, 2),
	"cc_type" text,
	"cc_mode" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"last_synced_at" timestamp,
	"vagaro_created_by" text,
	CONSTRAINT "transactions_vagaro_user_payment_id_unique" UNIQUE("vagaro_user_payment_id")
);
--> statement-breakpoint
CREATE TABLE "vagaro_customers" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"vagaro_customer_id" text NOT NULL,
	"vagaro_business_ids" text,
	"vagaro_data" text,
	"first_name" text NOT NULL,
	"last_name" text NOT NULL,
	"email" text,
	"mobile_phone" text,
	"day_phone" text,
	"night_phone" text,
	"street_address" text,
	"city" text,
	"region_code" text,
	"region_name" text,
	"country_code" text,
	"country_name" text,
	"postal_code" text,
	"business_group_id" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"last_synced_at" timestamp,
	"vagaro_created_at" timestamp,
	"vagaro_modified_at" timestamp,
	CONSTRAINT "vagaro_customers_vagaro_customer_id_unique" UNIQUE("vagaro_customer_id")
);
