-- Generated SQL to update services with Vagaro service codes
-- Run this after the 0022_add_vagaro_service_code.sql migration

UPDATE services SET vagaro_service_code = '6XoR0' WHERE name = 'Classic Full Set of Lash Extensions';
UPDATE services SET vagaro_service_code = '6XoRW' WHERE name = 'Classic Lash Fill';
UPDATE services SET vagaro_service_code = '6XoS0' WHERE name = 'Classic Mini Fill';
UPDATE services SET vagaro_service_code = '6XoSW' WHERE name = 'Wet/Angel Style Full Set of Lash Extensions';
UPDATE services SET vagaro_service_code = '6fWO0' WHERE name = 'Wet/Angel Lash Fill';
UPDATE services SET vagaro_service_code = '6fWOW' WHERE name = 'Wet/Angel Style Mini Fill';
UPDATE services SET vagaro_service_code = '6fWP0' WHERE name = 'Hybrid Full Set of Lash Extensions';
UPDATE services SET vagaro_service_code = '6fWPW' WHERE name = 'Hybrid Lash Fill';
UPDATE services SET vagaro_service_code = '6fWQ0' WHERE name = 'Hybrid Mini Fill';
UPDATE services SET vagaro_service_code = '6fWQW' WHERE name = 'Volume Full Set of Lash Extensions';
UPDATE services SET vagaro_service_code = '6fWR0' WHERE name = 'Volume Lash Fill';
UPDATE services SET vagaro_service_code = '6fWRW' WHERE name = 'Volume Mini Fill';
UPDATE services SET vagaro_service_code = '6fWS0' WHERE name = 'Mega Volume Full Set';
UPDATE services SET vagaro_service_code = '6fWSW' WHERE name = 'Mega Volume Fill';
UPDATE services SET vagaro_service_code = '6fYO0' WHERE name = 'Mega Volume Mini Fill';
UPDATE services SET vagaro_service_code = '6fYOW' WHERE name = 'Colored Eyelash Extensions';
UPDATE services SET vagaro_service_code = '6fYP0' WHERE name = 'Removal';
UPDATE services SET vagaro_service_code = '6fYPW' WHERE name = 'Lash Lift & Tint';
UPDATE services SET vagaro_service_code = '6fYQ0' WHERE name = 'Lash Lift';
UPDATE services SET vagaro_service_code = '6fYQW' WHERE name = 'Lash Tint';
UPDATE services SET vagaro_service_code = '6fYR0' WHERE name = 'Lash Lift Reversal';
UPDATE services SET vagaro_service_code = '6fYRW' WHERE name = 'Brow Shaping (Wax + Tweeze + Trim)';
UPDATE services SET vagaro_service_code = '6fYS0' WHERE name = 'Brow Lamination & Tint';
UPDATE services SET vagaro_service_code = '6fYSW' WHERE name = 'Brow Tint';
UPDATE services SET vagaro_service_code = '6faOW' WHERE name = 'Brow Lamination';
UPDATE services SET vagaro_service_code = '6faP0' WHERE name = 'Post Lamination Maintenance';
UPDATE services SET vagaro_service_code = '6faPW' WHERE name = 'Brow Consultation';
UPDATE services SET vagaro_service_code = '6faQ0' WHERE name = 'Microblading (1st Appointment)';
UPDATE services SET vagaro_service_code = '6faQW' WHERE name = 'Microblading (2nd Perfecting Appointment)';
UPDATE services SET vagaro_service_code = '6faR0' WHERE name = 'Microblading (Annual Refresh)';
UPDATE services SET vagaro_service_code = '6faRW' WHERE name = 'Nanobrows (1st Appointment)';
UPDATE services SET vagaro_service_code = '6faS0' WHERE name = 'Nanobrows (2nd Perfecting Appointment)';
UPDATE services SET vagaro_service_code = '6faSW' WHERE name = 'Nanobrows (Annual Refresh)';
UPDATE services SET vagaro_service_code = '6fcO0' WHERE name = 'Faux Beauty Marks (1st Appointment)';
UPDATE services SET vagaro_service_code = '6fcOW' WHERE name = 'Faux Beauty Marks (2nd Perfecting Appointment)';
UPDATE services SET vagaro_service_code = '6fcP0' WHERE name = 'Faux Beauty Marks (Annual Refresh)';
UPDATE services SET vagaro_service_code = '6fcPW' WHERE name = 'Lip Blushing (1st Appointment)';
UPDATE services SET vagaro_service_code = '6fcQ0' WHERE name = 'Lip Blushing (2nd Perfecting Appointment)';
UPDATE services SET vagaro_service_code = '6fcQW' WHERE name = 'Lip Blushing (Annual Refresh)';
UPDATE services SET vagaro_service_code = '6fcR0' WHERE name = 'Faux Freckles (1st Appointment)';
UPDATE services SET vagaro_service_code = '6fcRW' WHERE name = 'Faux Freckles (2nd Perfecting Appointment)';
UPDATE services SET vagaro_service_code = '6fcS0' WHERE name = 'Faux Freckles (Annual Refresh)';
UPDATE services SET vagaro_service_code = '6fcSW' WHERE name = 'Permanent Makeup Consultation';
UPDATE services SET vagaro_service_code = '6feO0' WHERE name = 'Tattoos';
UPDATE services SET vagaro_service_code = '6feOW' WHERE name = 'Signature Facial';
UPDATE services SET vagaro_service_code = '6feP0' WHERE name = 'Age Gracefully Facial';
UPDATE services SET vagaro_service_code = '6fePW' WHERE name = 'Acne Fighting Facial';
UPDATE services SET vagaro_service_code = '6feQ0' WHERE name = 'Sooth and Calm Facial';
UPDATE services SET vagaro_service_code = '6feQW' WHERE name = 'Oxygen Deep Pore Facial';
UPDATE services SET vagaro_service_code = '6feR0' WHERE name = 'Citrus Refresher Facial';
UPDATE services SET vagaro_service_code = '6feRW' WHERE name = 'Tailored to You Facial';
UPDATE services SET vagaro_service_code = '6feS0' WHERE name = 'Acne Relief Facial';
UPDATE services SET vagaro_service_code = '6feSW' WHERE name = 'Celluma Facial';
UPDATE services SET vagaro_service_code = '6fgO0' WHERE name = 'Epicutis Facial';
UPDATE services SET vagaro_service_code = '6fgOW' WHERE name = 'Oasis Facial';
UPDATE services SET vagaro_service_code = '6fgP0' WHERE name = 'Rejuvenating Facial';
UPDATE services SET vagaro_service_code = '6fgPW' WHERE name = 'Dermaplaning Facial';
UPDATE services SET vagaro_service_code = '6fgQ0' WHERE name = 'Back Facial';
UPDATE services SET vagaro_service_code = '6fgQW' WHERE name = 'Clarifying Hydrafacial';
UPDATE services SET vagaro_service_code = '6fgR0' WHERE name = 'Customized Hydrafacial';
UPDATE services SET vagaro_service_code = '6fgRW' WHERE name = 'Glow and Go Hydrafacial';
UPDATE services SET vagaro_service_code = '6fgS0' WHERE name = 'Restorative Hydrafacial';
UPDATE services SET vagaro_service_code = '6fgSW' WHERE name = 'The Ultimate Hydrafacial';
UPDATE services SET vagaro_service_code = '6fiO0' WHERE name = 'Celluma LED Light Therapy';
UPDATE services SET vagaro_service_code = '6fiOW' WHERE name = 'Express Dermaplaning';
UPDATE services SET vagaro_service_code = '6fiP0' WHERE name = 'Hand and Arm Treatment';
UPDATE services SET vagaro_service_code = '6fiPW' WHERE name = 'Hydrojelly Mask';
UPDATE services SET vagaro_service_code = '6fiQ0' WHERE name = 'Lymphatic Drainage';
UPDATE services SET vagaro_service_code = '6fiQW' WHERE name = 'Fibroblast Skin Treatment';
UPDATE services SET vagaro_service_code = '6fiR0' WHERE name = 'Jet Plasma Skin Treatment';
UPDATE services SET vagaro_service_code = '6fiRW' WHERE name = 'Permanent Jewelry for 1-3 People/Pieces';
UPDATE services SET vagaro_service_code = '6fiS0' WHERE name = 'Permanent Jewelry for 4-6 People/Pieces';
UPDATE services SET vagaro_service_code = '6fiSW' WHERE name = 'Permanent Jewelry Re-Weld';
UPDATE services SET vagaro_service_code = '6fkO0' WHERE name = 'Arm Wax (Full)';
UPDATE services SET vagaro_service_code = '6fkOW' WHERE name = 'Arm Wax (Half)';
UPDATE services SET vagaro_service_code = '6fkP0' WHERE name = 'Brazilian Wax';
UPDATE services SET vagaro_service_code = '6fkPW' WHERE name = 'Brow Shaping (Wax + Tweeze + Trim)';
UPDATE services SET vagaro_service_code = '6fkQ0' WHERE name = 'Chin Wax';
UPDATE services SET vagaro_service_code = '6fkQW' WHERE name = 'Full Face Wax';
UPDATE services SET vagaro_service_code = '6fkR0' WHERE name = 'Leg Wax (Full)';
UPDATE services SET vagaro_service_code = '6fkRW' WHERE name = 'Leg Wax (Half)';
UPDATE services SET vagaro_service_code = '6fkS0' WHERE name = 'Upper Lip and Chin Wax';
UPDATE services SET vagaro_service_code = '6fkSW' WHERE name = 'Lower Back Wax';
UPDATE services SET vagaro_service_code = '6fmO0' WHERE name = 'Nose Wax';
UPDATE services SET vagaro_service_code = '6fmOW' WHERE name = 'Sideburn Wax';
UPDATE services SET vagaro_service_code = '6fmP0' WHERE name = 'Underarm Wax';
UPDATE services SET vagaro_service_code = '6fmPW' WHERE name = 'Upper Lip Wax';
UPDATE services SET vagaro_service_code = '6fmQ0' WHERE name = 'Lash Lift & Tint Bundle';
UPDATE services SET vagaro_service_code = '6fmQW' WHERE name = 'Brow Lamination & Tint Bundle';
UPDATE services SET vagaro_service_code = '6fmR0' WHERE name = 'Facial Wax & Brow Tint Bundle';
UPDATE services SET vagaro_service_code = '6fmRW' WHERE name = 'Brow Shaping & Tint Bundle';
UPDATE services SET vagaro_service_code = '6fmS0' WHERE name = 'Brow Lamination & Lash Lift Bundle';
UPDATE services SET vagaro_service_code = '6fmSW' WHERE name = 'Brazilian & Underarms Wax';
UPDATE services SET vagaro_service_code = '6foO0' WHERE name = 'Brazilian & Brow Wax';
UPDATE services SET vagaro_service_code = '6foOW' WHERE name = 'Lashpop Pro Training';
