export type OwnerGuideArea = "Start here" | "Website" | "Reviews" | "Media" | "Inbox" | "Settings"

export interface OwnerGuideStep {
  title: string
  detail: string
  focus?: "top" | "middle" | "bottom"
  outsideAdmin?: boolean
}

export interface OwnerGuideArticle {
  id: string
  capabilityId: string
  area: OwnerGuideArea
  title: string
  questions: string[]
  summary: string
  route: string
  screen: string
  screenshot: string
  screenshotAlt: string
  keywords: string[]
  before?: string[]
  steps: OwnerGuideStep[]
  check: string[]
  warning?: string
}

export const OWNER_GUIDE_AREAS: OwnerGuideArea[] = ["Start here", "Website", "Reviews", "Media", "Inbox", "Settings"]

export const OWNER_GUIDE_ARTICLES: OwnerGuideArticle[] = [
  {
    id: "sign-in",
    capabilityId: "access-sign-in",
    area: "Start here",
    title: "Sign in or sign out",
    questions: ["How do I sign in with my phone number?", "How do I sign out when I am finished?"],
    summary: "Use your approved phone number to open LashPop Admin. Sign out when you finish on a shared device.",
    route: "/admin/login",
    screen: "Sign in",
    screenshot: "/admin-guide/screenshots/01-sign-in.png",
    screenshotAlt: "The LashPop Admin sign-in page with a phone number box and Send code button.",
    keywords: ["login", "code", "text message", "phone", "logout"],
    before: ["Use the phone number that has LashPop Admin access.", "Keep your phone nearby so you can receive the sign-in code."],
    steps: [
      { title: "Enter your phone number", detail: "Type the full phone number in the Phone number box.", focus: "middle" },
      { title: "Ask for a code", detail: "Select Send code. Wait for the text message before asking for another code.", focus: "middle" },
      { title: "Enter the code", detail: "Type the code from the text message. LashPop Admin opens on the Today page.", focus: "bottom" },
      { title: "Sign out when needed", detail: "Open the account area at the bottom of the menu and select Sign out.", focus: "bottom" },
    ],
    check: ["You can see the Today page after signing in.", "A signed-out browser returns to the sign-in page."],
    warning: "Never share a sign-in code. LashPop staff will not ask you to send one.",
  },
  {
    id: "today",
    capabilityId: "today-overview",
    area: "Start here",
    title: "See what needs attention today",
    questions: ["Where do I see what needs attention today?"],
    summary: "Start here to see new enquiries, recent changes and whether the Vagaro update is healthy.",
    route: "/admin/overview",
    screen: "Today → Operations overview",
    screenshot: "/admin-guide/screenshots/02-today-overview.png",
    screenshotAlt: "The Today page showing health, inbox totals and recent changes.",
    keywords: ["dashboard", "tasks", "health", "new", "recent"],
    steps: [
      { title: "Open Today", detail: "Select Today in the main menu.", focus: "top" },
      { title: "Read the warning first", detail: "If you see a warning, open it before publishing website changes.", focus: "top" },
      { title: "Check new activity", detail: "Review newsletter signups, applications and recent admin changes.", focus: "middle" },
      { title: "Open the work you need", detail: "Select a card to go straight to that part of Admin.", focus: "bottom" },
    ],
    check: ["You know whether the site needs attention.", "You have opened each new item that needs a response."],
  },
  {
    id: "find-help",
    capabilityId: "owner-guide",
    area: "Start here",
    title: "Find help in LashPop Admin",
    questions: ["How do I find help in the admin panel?"],
    summary: "Search by the job you want to complete, or browse a work area.",
    route: "/admin/owner-guide",
    screen: "Owner guide",
    screenshot: "/admin-guide/screenshots/28-owner-guide.png",
    screenshotAlt: "The Owner guide with a search box, work-area filters and task cards.",
    keywords: ["help", "guide", "instructions", "search", "how do I"],
    steps: [
      { title: "Open Owner guide", detail: "Select Owner guide under Settings.", focus: "top" },
      { title: "Search for your task", detail: "Type what you want to do, such as change a team photo or add a service.", focus: "top" },
      { title: "Choose a result", detail: "Select the task that best matches what you need.", focus: "middle" },
      { title: "Follow each step", detail: "Use the numbered instructions and screenshot. Select Open this page when you are ready to work.", focus: "bottom" },
    ],
    check: ["The guide shows a task that matches your search.", "The Open this page link takes you to the correct Admin screen."],
  },
  {
    id: "website-ownership",
    capabilityId: "website-overview",
    area: "Website",
    title: "Know where to make a website change",
    questions: ["Where do I see which system owns each part of the website?"],
    summary: "Use the Website overview to learn whether to make a change in LashPop Admin or Vagaro.",
    route: "/admin/website",
    screen: "Website → Website overview",
    screenshot: "/admin-guide/screenshots/03-website-overview.png",
    screenshotAlt: "The Website overview showing each website area and where to make changes.",
    keywords: ["where", "ownership", "Vagaro", "LashPop", "change"],
    steps: [
      { title: "Open Website", detail: "Select Website, then Website overview.", focus: "top" },
      { title: "Find the part you want to change", detail: "Look for the card that matches the page or content.", focus: "middle" },
      { title: "Read where the change belongs", detail: "LashPop means change it here. Vagaro means change it in Vagaro first. Mixed means both places are involved.", focus: "middle" },
      { title: "Open the correct page", detail: "Select the card to continue.", focus: "bottom" },
    ],
    check: ["You know which system owns the information.", "You have not entered the same change in two places."],
  },
  {
    id: "launch-service",
    capabilityId: "service-launch",
    area: "Website",
    title: "Add or update a service",
    questions: ["How do I add or update a service in Vagaro, sync it, and know what still needs technical publication?", "How do I check that a new or updated service is ready to publish?"],
    summary: "Set up the service in Vagaro, bring the latest details into LashPop, then complete every launch check.",
    route: "/admin/workflows/service-launch",
    screen: "Website → Launch a service",
    screenshot: "/admin-guide/screenshots/04a-add-service-workflow.png",
    screenshotAlt: "The service launch guide with the Vagaro setup checklist and LashPop checks.",
    keywords: ["new service", "price", "booking", "publish", "Vagaro", "launch"],
    before: ["Have the final service name, category, price, length and list of providers.", "Use a computer for the Vagaro setup."],
    steps: [
      { title: "Set up the service in Vagaro", detail: "In Vagaro, open Settings, then Service/Class Menu. Add or edit the service, turn on online booking and choose every provider who offers it.", outsideAdmin: true },
      { title: "Confirm the Vagaro work", detail: "Return to LashPop. Read the checklist, tick the confirmation box and select Sync from Vagaro.", focus: "top" },
      { title: "Find the service", detail: "Choose the service category and select Check service.", focus: "middle" },
      { title: "Complete each launch check", detail: "Review booking, wording, photos, homepage card and eligible team members. Open each incomplete item from the checklist.", focus: "middle" },
      { title: "Ask for the booking connection", detail: "For a brand-new service, send the exact service name and Vagaro category to the website manager. Keep it hidden until they confirm the booking button is ready.", focus: "bottom" },
      { title: "Test before showing it", detail: "Open both customer links. Test the service page and booking path on a phone and computer.", focus: "bottom" },
    ],
    check: ["The service opens the correct booking screen.", "Only the correct providers appear.", "The service wording, image and homepage card are correct."],
    warning: "Do not copy another service's booking link. A wrong link can send customers to the wrong appointment.",
  },
  {
    id: "studio-details",
    capabilityId: "studio-info",
    area: "Website",
    title: "Change studio contact details or hours",
    questions: ["How do I update the studio address, phone number, email, hours, booking link, map location, or social links?"],
    summary: "Change the details that appear in the footer, map, contact links and search results.",
    route: "/admin/content/studio-info",
    screen: "Website → Studio information",
    screenshot: "/admin-guide/screenshots/05-studio-information.png",
    screenshotAlt: "The Studio information page with address, phone, hours and social-link fields.",
    keywords: ["address", "hours", "phone", "email", "map", "social"],
    before: ["Confirm the new details from an official source.", "Have full web addresses ready for booking and social links."],
    steps: [
      { title: "Open Studio information", detail: "Select Website, then Studio information.", focus: "top" },
      { title: "Change only what is different", detail: "Review the address, phone, email, hours, booking link, map point and social links.", focus: "middle" },
      { title: "Check links and map numbers", detail: "Make sure every web address starts with https://. Check the map point carefully.", focus: "middle" },
      { title: "Save the changes", detail: "Select Save.", focus: "bottom" },
      { title: "Check the public site", detail: "Open the footer, map and contact links on the website. Test them on a phone.", focus: "bottom" },
    ],
    check: ["The footer shows the new details.", "Phone, email, map and booking links open correctly.", "The studio pin appears in the right place."],
  },
  {
    id: "homepage-hero",
    capabilityId: "homepage-hero",
    area: "Website",
    title: "Change the homepage headline or hero photos",
    questions: ["How do I change the homepage headline or button labels?", "How do I choose the homepage hero photos and control the desktop and phone slideshow?"],
    summary: "Update the first words and photos people see when they open the website.",
    route: "/admin/website/hero",
    screen: "Website → Homepage hero",
    screenshot: "/admin-guide/screenshots/06-homepage-hero.png",
    screenshotAlt: "The Homepage hero page with wording, slideshow and phone and computer choices.",
    keywords: ["headline", "button", "hero", "slideshow", "mobile", "desktop"],
    before: ["Have approved wording and high-quality photos ready.", "Check that each photo works in both a wide and tall space."],
    steps: [
      { title: "Open Homepage hero", detail: "Select Website, then Homepage hero.", focus: "top" },
      { title: "Update the words", detail: "Change the headline, supporting line or button labels in Hero content.", focus: "top" },
      { title: "Choose the photos", detail: "Open the slideshow settings. Add approved photos and place the main subject inside the safe area.", focus: "middle" },
      { title: "Set phone and computer versions", detail: "Choose which slideshow appears on each screen size. Use the same one only when every crop still looks good.", focus: "middle" },
      { title: "Publish and check", detail: "Save the settings. Open the homepage on a phone and computer and watch the full slideshow once.", focus: "bottom" },
    ],
    check: ["The headline and buttons say exactly what you approved.", "Faces and important details are not cut off.", "The first photo appears quickly on a fresh page load."],
    warning: "The homepage hero affects every visitor. Check both screen sizes before you finish.",
  },
  {
    id: "services-booking",
    capabilityId: "services-booking",
    area: "Website",
    title: "Review services and booking",
    questions: ["How do I review synced services, choose service images, organize service groups, and confirm booking readiness?", "What comes from Vagaro, what can I edit in LashPop, and why can a new service stay hidden?"],
    summary: "Review the service details copied from Vagaro and the way LashPop presents them on the website.",
    route: "/admin/website/services",
    screen: "Website → Services & booking",
    screenshot: "/admin-guide/screenshots/07-services-booking.png",
    screenshotAlt: "The Services and booking page showing service groups, photos and booking readiness.",
    keywords: ["service", "booking", "group", "image", "hidden", "pending"],
    steps: [
      { title: "Change booking facts in Vagaro", detail: "Change names, prices, appointment length, availability and providers in Vagaro.", outsideAdmin: true },
      { title: "Bring the latest details into LashPop", detail: "Open Settings, then Vagaro sync. Run the update only after the Vagaro changes are complete.", focus: "top" },
      { title: "Open Services & booking", detail: "Review the category, order, description and image for each changed service.", focus: "middle" },
      { title: "Read the booking status", detail: "Ready means the booking button has been checked. Pending means the service must stay hidden until the website manager finishes the connection.", focus: "middle" },
      { title: "Save the website presentation", detail: "Save local wording, image and order changes.", focus: "bottom" },
    ],
    check: ["Prices and appointment lengths match Vagaro.", "The correct image and description appear.", "Every visible service has a Ready booking status."],
  },
  {
    id: "homepage-service-cards",
    capabilityId: "homepage-service-cards",
    area: "Website",
    title: "Change homepage service cards",
    questions: ["How do I add, edit, reorder, show, or hide a service card on the homepage?"],
    summary: "Control the service choices shown in the Choose a service section.",
    route: "/admin/website/homepage-services",
    screen: "Website → Homepage service cards",
    screenshot: "/admin-guide/screenshots/08-homepage-service-cards.png",
    screenshotAlt: "The Homepage service cards page with wording, order and visibility controls.",
    keywords: ["card", "choose a service", "order", "show", "hide", "icon"],
    steps: [
      { title: "Open Homepage service cards", detail: "Select Website, then Homepage service cards.", focus: "top" },
      { title: "Choose a card", detail: "Edit its title, short line, description, icon or destination.", focus: "middle" },
      { title: "Set the order and visibility", detail: "Use the arrow controls to move it. Use the eye control to show or hide it.", focus: "middle" },
      { title: "Save changes", detail: "Select Save changes.", focus: "bottom" },
      { title: "Test every changed card", detail: "Open the homepage and select each card you changed.", focus: "bottom" },
    ],
    check: ["Cards appear in the intended order.", "Hidden cards do not appear.", "Every visible card opens the correct service."],
  },
  {
    id: "team-stylists",
    capabilityId: "team-stylists",
    area: "Website",
    title: "Add, update or publish a team member",
    questions: ["How do I add a new team member in Vagaro and publish them safely?", "How do I update a staff member?", "How do I sync a stylist from Vagaro?", "How do I show, hide, or reorder staff on the website?", "How do I update an external stylist's photo, bio, service tags, portfolio, quick facts, or credentials?"],
    summary: "Keep each profile accurate, choose who appears on the website and put the team in the right order.",
    route: "/admin/website/team",
    screen: "Website → Team & stylists",
    screenshot: "/admin-guide/screenshots/09a-add-team-member-workflow.png",
    screenshotAlt: "The Team and stylists page with the new-person checklist, profile cards and visibility controls.",
    keywords: ["staff", "stylist", "team", "bio", "services", "publish", "hide", "order"],
    before: ["For a Vagaro team member, finish their profile and services in Vagaro first.", "Have approval for the public photo and biography."],
    steps: [
      { title: "Set up a new Vagaro team member", detail: "In Vagaro, add the employee profile, public photo, biography, services and prices. Turn on online booking.", outsideAdmin: true },
      { title: "Bring the latest profile into LashPop", detail: "Open Team & stylists. Confirm the Vagaro work, then select Sync from Vagaro.", focus: "top" },
      { title: "Review the profile while it is hidden", detail: "Check the photo, biography, services, contact details and booking link. New people stay hidden until you approve them.", focus: "middle" },
      { title: "Add LashPop-only details", detail: "Add portfolio photos, quick facts or credentials when needed. For someone who does not use Vagaro, you can also edit their main photo, biography and service labels here.", focus: "middle" },
      { title: "Choose visibility and order", detail: "Use the eye control to show or hide the person. Move cards into the order you want.", focus: "middle" },
      { title: "Save and test", detail: "Add a short reason when asked, save changes, then open the public team section and test the booking path.", focus: "bottom" },
    ],
    check: ["The right people appear in the right order.", "Each visible profile has the approved photo and words.", "Services and booking match Vagaro."],
    warning: "Do not show a new profile until you have checked the public photo, services and booking path.",
  },
  {
    id: "founder-letter",
    capabilityId: "founder-letter",
    area: "Website",
    title: "Update the founder letter",
    questions: ["How do I update the founder letter?"],
    summary: "Change Emily's message on the homepage and review the full letter before saving.",
    route: "/admin/content/founder-letter",
    screen: "Website → Founder letter",
    screenshot: "/admin-guide/screenshots/10-founder-letter.png",
    screenshotAlt: "The Founder letter editor with wording fields and a preview.",
    keywords: ["Emily", "letter", "message", "paragraph", "signature"],
    steps: [
      { title: "Open Founder letter", detail: "Select Website, then Founder letter.", focus: "top" },
      { title: "Edit the message", detail: "Change the heading, greeting, paragraphs, sign-off or signature.", focus: "middle" },
      { title: "Read the preview from start to finish", detail: "Check names, paragraph order, punctuation and line breaks.", focus: "middle" },
      { title: "Save and check the homepage", detail: "Select Save. Open the homepage on a phone and computer.", focus: "bottom" },
    ],
    check: ["The full message appears in the right order.", "No paragraph is missing or repeated.", "The signature looks correct on both screen sizes."],
  },
  {
    id: "founder-letter-old-link",
    capabilityId: "founder-letter-redirect",
    area: "Website",
    title: "Use an old founder-letter link",
    questions: ["Where does the old founder-letter admin link take me?"],
    summary: "The old link now opens the current Founder letter editor.",
    route: "/admin/website/founder-letter",
    screen: "Website → Founder letter",
    screenshot: "/admin-guide/screenshots/10-founder-letter.png",
    screenshotAlt: "The current Founder letter editor opened from the old link.",
    keywords: ["old link", "redirect", "founder"],
    steps: [
      { title: "Open the old link", detail: "Use the saved link as normal.", focus: "top" },
      { title: "Continue in the current editor", detail: "LashPop sends you to Website, then Founder letter. There is only one current editor.", focus: "middle" },
      { title: "Update your bookmark", detail: "Save the new page if you keep Admin bookmarks.", focus: "bottom" },
    ],
    check: ["The page title says Founder letter.", "You do not see two different editors."],
  },
  {
    id: "instagram",
    capabilityId: "instagram",
    area: "Website",
    title: "Change the Instagram carousel",
    questions: ["How do I control how many Instagram posts appear, whether captions show, and how the carousel moves?", "How do I refresh the Instagram posts already available in the media library?"],
    summary: "Choose how the homepage Instagram row behaves and refresh the saved posts.",
    route: "/admin/website/instagram",
    screen: "Website → Instagram",
    screenshot: "/admin-guide/screenshots/11-instagram.png",
    screenshotAlt: "The Instagram page with post count, captions, movement and refresh controls.",
    keywords: ["Instagram", "carousel", "caption", "speed", "posts", "refresh"],
    steps: [
      { title: "Open Instagram", detail: "Select Website, then Instagram.", focus: "top" },
      { title: "Choose what people see", detail: "Set the number of posts and choose whether captions appear.", focus: "middle" },
      { title: "Choose how it moves", detail: "Turn automatic movement on or off and set a comfortable speed.", focus: "middle" },
      { title: "Refresh saved posts when needed", detail: "Select Sync posts to bring the latest available Instagram posts into the media library.", focus: "middle" },
      { title: "Save and watch the full row", detail: "Save changes. Open the homepage and watch the carousel on a phone and computer.", focus: "bottom" },
    ],
    check: ["The intended number of posts appears.", "Captions follow your setting.", "Movement is smooth and not distracting."],
  },
  {
    id: "faq",
    capabilityId: "faq",
    area: "Website",
    title: "Add or change a frequently asked question",
    questions: ["How do I add or change an FAQ?", "How do I organize FAQs into categories and choose which ones are visible or featured?"],
    summary: "Write clear answers, group related questions and choose what appears on the website.",
    route: "/admin/website/faq",
    screen: "Website → FAQ",
    screenshot: "/admin-guide/screenshots/12-faq.png",
    screenshotAlt: "The FAQ page with categories, questions, visibility and featured controls.",
    keywords: ["FAQ", "question", "answer", "category", "featured", "visible"],
    steps: [
      { title: "Open FAQ", detail: "Select Website, then FAQ.", focus: "top" },
      { title: "Choose a category", detail: "Open the category that best matches the question. Add a category only when none fits.", focus: "middle" },
      { title: "Add or edit the question", detail: "Use the words a customer would use. Give the answer first, then add only the detail they need.", focus: "middle" },
      { title: "Choose visibility", detail: "Turn on Visible when the answer is ready. Use Featured only for the questions most customers need.", focus: "middle" },
      { title: "Save and read it on the website", detail: "Save the question. Open the public FAQ and read the answer on a phone.", focus: "bottom" },
    ],
    check: ["The question is in the right category.", "The answer is short, clear and current.", "Visibility and Featured settings are correct."],
    warning: "Deleting removes the question. Hide it instead when you may need the wording or history later.",
  },
  {
    id: "quiz",
    capabilityId: "quiz",
    area: "Website",
    title: "Change Find Your Look quiz photos or results",
    questions: ["How do I add, crop, enable, or remove quiz comparison photos?", "How do I choose the photo and wording shown for each quiz result?"],
    summary: "Manage the photos people compare and the result they see at the end.",
    route: "/admin/website/quiz",
    screen: "Website → Find Your Look",
    screenshot: "/admin-guide/screenshots/13-find-your-look.png",
    screenshotAlt: "The Find Your Look page with comparison photos, crop tools and result settings.",
    keywords: ["quiz", "lash", "classic", "hybrid", "volume", "wet angel", "result", "crop"],
    before: ["Know which lash style each photo represents.", "Use the approved result photo and wording for each style."],
    steps: [
      { title: "Open Find Your Look", detail: "Select Website, then Find Your Look.", focus: "top" },
      { title: "Add and label comparison photos", detail: "Upload the photo, choose the correct lash style and add a clear internal name.", focus: "middle" },
      { title: "Set the crop", detail: "Keep the whole eye and lash shape visible. Check the crop in every preview shape before saving.", focus: "middle" },
      { title: "Choose which photos can appear", detail: "Enable approved photos. Disable a photo instead of deleting it when you may need it later.", focus: "middle" },
      { title: "Set each result", detail: "Choose the final photo, heading and description for Classic, Hybrid, Volume and Wet/Angel.", focus: "bottom" },
      { title: "Test four clear paths", detail: "Take the public quiz once for each style. Confirm the result and final photo match your choices.", focus: "bottom" },
    ],
    check: ["Every photo has the correct style label.", "No eye edge is cut off.", "Each clear answer path gives the correct result and photo."],
    warning: "Quiz changes affect the recommendation. Test all four styles before you finish.",
  },
  {
    id: "work-with-us",
    capabilityId: "work-with-us",
    area: "Website",
    title: "Change the Work With Us page",
    questions: ["How do I update the Work With Us introduction and its employee, booth, and training summaries?", "How do I add, show, hide, or remove Work With Us photos?"],
    summary: "Update the page introduction, path summaries and photo carousel.",
    route: "/admin/website/work-with-us",
    screen: "Website → Work With Us",
    screenshot: "/admin-guide/screenshots/14-work-with-us.png",
    screenshotAlt: "The Work With Us page with introduction, path summaries and photo controls.",
    keywords: ["careers", "jobs", "booth", "training", "employee", "photos"],
    steps: [
      { title: "Open Work With Us", detail: "Select Website, then Work With Us.", focus: "top" },
      { title: "Update the introduction", detail: "Explain who LashPop is looking for and what someone should do next.", focus: "top" },
      { title: "Review the three paths", detail: "Update the short summaries for employee, booth rental and training. Do not change benefits, prices or policy promises here.", focus: "middle" },
      { title: "Manage the photos", detail: "Add approved photos, choose what appears, change the order or hide an image.", focus: "middle" },
      { title: "Save and check the page", detail: "Open the public page on a phone and computer. Read every path and watch the full photo row.", focus: "bottom" },
    ],
    check: ["The introduction and three summaries are current.", "Photos load in the intended order.", "Application buttons still open the correct form."],
    warning: "Benefits, prices, forms and policy wording need a reviewed website change. Do not promise new terms in the summary fields.",
  },
  {
    id: "search-sharing",
    capabilityId: "search-sharing",
    area: "Website",
    title: "Change search and social-share wording",
    questions: ["How do I update the words and images people see in Google results and social shares?"],
    summary: "Update page titles, descriptions and share images without changing the visible page copy.",
    route: "/admin/website/seo",
    screen: "Website → Search & sharing",
    screenshot: "/admin-guide/screenshots/15-search-sharing.png",
    screenshotAlt: "The Search and sharing page with page titles, descriptions and social images.",
    keywords: ["Google", "search", "title", "description", "share image", "social"],
    steps: [
      { title: "Open Search & sharing", detail: "Select Website, then Search & sharing.", focus: "top" },
      { title: "Choose the page", detail: "Open the page whose search or share preview you want to change.", focus: "middle" },
      { title: "Write the title and description", detail: "Say what the page offers in plain language. Put the most useful words first.", focus: "middle" },
      { title: "Choose the share image", detail: "Use an approved image that stays clear when cropped wide.", focus: "middle" },
      { title: "Save and preview", detail: "Save the settings. Use the preview to check for cut-off words or images.", focus: "bottom" },
    ],
    check: ["The title names the page clearly.", "The description is accurate and not repetitive.", "The share image has no important detail near the edge."],
  },
  {
    id: "reviews",
    capabilityId: "reviews",
    area: "Reviews",
    title: "Choose and correct website reviews",
    questions: ["How do I choose and reorder the reviews shown on the homepage?", "How do I correct a review's website visibility, stylist, score, or editor notes without automation overwriting it?"],
    summary: "Choose the reviews people see and lock an approved correction when the automatic choice is wrong.",
    route: "/admin/website/reviews",
    screen: "Reviews & reputation → Review library",
    screenshot: "/admin-guide/screenshots/16-review-library.png",
    screenshotAlt: "The Review library with homepage choices, order and edit controls.",
    keywords: ["review", "homepage", "rating", "stylist", "pin", "lock"],
    steps: [
      { title: "Open Review library", detail: "Select Reviews & reputation, then Review library.", focus: "top" },
      { title: "Find the review", detail: "Search by customer, words in the review or stylist.", focus: "middle" },
      { title: "Choose homepage reviews", detail: "Add or remove the review from the homepage and place chosen reviews in the order you want.", focus: "middle" },
      { title: "Correct a wrong detail", detail: "Open the review. Change visibility, stylist, score or notes only when you have checked the source.", focus: "middle" },
      { title: "Save and lock an approved correction", detail: "Use Save and lock when the automatic review update must not replace your correction.", focus: "bottom" },
    ],
    check: ["The intended reviews appear on the homepage.", "Names and stylist links are correct.", "Only approved corrections are locked."],
    warning: "A locked correction will not update automatically. Unlock it when the correction is no longer needed.",
  },
  {
    id: "review-automation",
    capabilityId: "review-automation",
    area: "Reviews",
    title: "Change automatic review choices",
    questions: ["How do I change the rules that score and rotate reviews?"],
    summary: "Control how LashPop scores reviews and refreshes the automatic homepage selection.",
    route: "/admin/website/review-settings",
    screen: "Reviews & reputation → Automation",
    screenshot: "/admin-guide/screenshots/17-review-automation.png",
    screenshotAlt: "The review Automation page with scoring and rotation settings.",
    keywords: ["reviews", "automatic", "score", "rotate", "rules"],
    before: ["Know the result you want and which reviews would be affected.", "Record the current settings before changing them."],
    steps: [
      { title: "Open Automation", detail: "Select Reviews & reputation, then Automation.", focus: "top" },
      { title: "Change one rule at a time", detail: "Adjust the score or rotation setting you need. Leave unrelated settings alone.", focus: "middle" },
      { title: "Save the settings", detail: "Review the numbers once more, then select Save.", focus: "bottom" },
      { title: "Check the next result", detail: "Review the homepage choices after the next automatic update.", focus: "bottom" },
    ],
    check: ["The saved values match what you intended.", "Pinned reviews stay in place.", "The automatic selection still contains suitable reviews."],
    warning: "These settings can change many reviews at once. Make small changes and check the result.",
  },
  {
    id: "media-library",
    capabilityId: "media-library",
    area: "Media",
    title: "Upload and organise website media",
    questions: ["How do I upload photos or videos?", "How do I search, filter, tag, describe, group, or assign media for reuse around the website?"],
    summary: "Keep approved photos and videos easy to find, understand and reuse.",
    route: "/admin/assets",
    screen: "Media → Asset library",
    screenshot: "/admin-guide/screenshots/18-media-library.png",
    screenshotAlt: "The Asset library with upload, search, filters, tags and image details.",
    keywords: ["photo", "video", "upload", "tag", "collection", "alt text", "caption"],
    before: ["Use the original high-quality file.", "Confirm you have permission to use it on the website."],
    steps: [
      { title: "Open Asset library", detail: "Select Media, then Asset library.", focus: "top" },
      { title: "Upload the files", detail: "Select Upload files and choose the approved photos or videos. Wait for every upload to finish.", focus: "top" },
      { title: "Add a useful description", detail: "Open each item. Add alt text that describes the image for someone who cannot see it. Add a caption or internal note when helpful.", focus: "middle" },
      { title: "Make it easy to find", detail: "Add the right person, service, tag or collection. Use words the team will search for later.", focus: "middle" },
      { title: "Check the file", detail: "Open the large preview. Make sure it is sharp, upright and the intended file.", focus: "bottom" },
    ],
    check: ["The file opens without an error.", "Alt text explains the important content.", "Search and filters can find the item."],
    warning: "Deleting a media item can remove it from several places. Check its assignments first.",
  },
  {
    id: "team-photography",
    capabilityId: "team-photography",
    area: "Media",
    title: "Manage a team member's portrait and album",
    questions: ["How do I upload, crop, choose the primary photo, or manage the photo album for a team member?"],
    summary: "See the portrait used on the website and prepare local photos and crops for each team member.",
    route: "/admin/assets/team",
    screen: "Media → Team photography",
    screenshot: "/admin-guide/screenshots/19-team-photography.png",
    screenshotAlt: "The Team photography page with website portraits, local photos and crop controls.",
    keywords: ["portrait", "headshot", "team photo", "change a team photo", "crop", "primary", "album"],
    steps: [
      { title: "Open Team photography", detail: "Select Media, then Team photography.", focus: "top" },
      { title: "Choose the person", detail: "The card shows the portrait currently used on the website. Select the person to open their photo library.", focus: "middle" },
      { title: "Upload an approved source photo", detail: "Select Upload photos and choose the original file.", focus: "top" },
      { title: "Set every crop", detail: "Open Set crops. Keep the face and important details inside each preview shape, then save all crops.", focus: "middle" },
      { title: "Choose the local primary", detail: "Select Make primary on the prepared photo. If the profile comes from Vagaro, the page will tell you that Vagaro still supplies the live website portrait.", focus: "middle" },
      { title: "Check the website portrait", detail: "Compare the Live website portrait panel with the public team card.", focus: "bottom" },
    ],
    check: ["The live portrait matches the public website.", "The local primary file opens.", "All crop previews keep the face inside the frame."],
  },
  {
    id: "inbox-overview",
    capabilityId: "inbox-overview",
    area: "Inbox",
    title: "See new signups and applications",
    questions: ["Where do I see new newsletter signups and Work With Us applications?"],
    summary: "Use one page to see new people who have signed up or applied.",
    route: "/admin/inbox",
    screen: "Inbox → Inbox overview",
    screenshot: "/admin-guide/screenshots/20-inbox-overview.png",
    screenshotAlt: "The Inbox overview with newsletter and application totals.",
    keywords: ["inbox", "new", "signup", "application", "newsletter"],
    steps: [
      { title: "Open Inbox", detail: "Select Inbox, then Inbox overview.", focus: "top" },
      { title: "Check the totals", detail: "Review newsletter signups and Work With Us applications.", focus: "middle" },
      { title: "Open a list", detail: "Select the card for the people you need to review.", focus: "middle" },
      { title: "Handle the oldest new item first", detail: "Work through new records in date order unless one is urgent.", focus: "bottom" },
    ],
    check: ["You have opened every new item.", "You have not copied or contacted anyone without a clear reason."],
  },
  {
    id: "newsletter",
    capabilityId: "newsletter",
    area: "Inbox",
    title: "Find and manage newsletter subscribers",
    questions: ["How do I find a newsletter subscriber and understand their consent status?", "How do I copy or export only active subscribers?", "How do I mark a subscriber active, unsubscribed, or suppressed without erasing history?"],
    summary: "Search the consent list, export active subscribers and keep an accurate history when a status changes.",
    route: "/admin/inbox/newsletter",
    screen: "Inbox → Newsletter subscribers",
    screenshot: "/admin-guide/screenshots/21-newsletter.png",
    screenshotAlt: "The Newsletter subscribers page with search, consent status and active-only export controls.",
    keywords: ["subscriber", "email", "consent", "active", "unsubscribe", "suppressed", "export"],
    steps: [
      { title: "Open Newsletter subscribers", detail: "Select Inbox, then Newsletter subscribers.", focus: "top" },
      { title: "Find the person", detail: "Search by email address or use the status filter.", focus: "top" },
      { title: "Read the consent history", detail: "Check when and how the person signed up before changing anything.", focus: "middle" },
      { title: "Change status without deleting", detail: "Use Active, Unsubscribed or Suppressed. Keep the record so LashPop retains the consent history.", focus: "middle" },
      { title: "Copy or export active subscribers", detail: "Choose the active-only copy or export control. Check the active filter before using the list.", focus: "bottom" },
    ],
    check: ["Only active subscribers are included in a marketing list.", "Unsubscribed and suppressed people remain excluded.", "The history record still exists."],
    warning: "Never add an unsubscribed or suppressed person back to a marketing list without new consent.",
  },
  {
    id: "applications",
    capabilityId: "applications",
    area: "Inbox",
    title: "Read a Work With Us application",
    questions: ["How do I read the details and contact information from a Work With Us application?"],
    summary: "Review an applicant's submitted answers and contact details in one place.",
    route: "/admin/inbox/work-with-us",
    screen: "Inbox → Applications",
    screenshot: "/admin-guide/screenshots/22-applications.png",
    screenshotAlt: "The Applications page with an applicant summary and submitted details.",
    keywords: ["application", "applicant", "contact", "work", "job", "booth"],
    steps: [
      { title: "Open Applications", detail: "Select Inbox, then Applications.", focus: "top" },
      { title: "Choose an application", detail: "Use the date and application type to find the person you need.", focus: "middle" },
      { title: "Read the full submission", detail: "Review their contact details, experience, interests and answers before taking notes elsewhere.", focus: "middle" },
      { title: "Use the approved contact process", detail: "Contact the person only when LashPop has decided who should respond and how.", focus: "bottom" },
    ],
    check: ["You reviewed the complete application.", "Contact details were not shared outside the people who need them."],
    warning: "Applications contain private information. Do not download, forward or copy details unless the work requires it.",
  },
  {
    id: "settings-overview",
    capabilityId: "settings-overview",
    area: "Settings",
    title: "Check your access and Vagaro health",
    questions: ["Where do I check my access level and the latest Vagaro sync?"],
    summary: "See what your Admin role allows and whether the latest Vagaro update completed.",
    route: "/admin/settings",
    screen: "Settings → Settings overview",
    screenshot: "/admin-guide/screenshots/23-settings-overview.png",
    screenshotAlt: "The Settings overview showing the current role and latest Vagaro update.",
    keywords: ["role", "access", "owner", "publisher", "viewer", "Vagaro", "health"],
    steps: [
      { title: "Open Settings", detail: "Select Settings, then Settings overview.", focus: "top" },
      { title: "Check your role", detail: "Your role appears in the Access card. Owner, Publisher and Viewer have different permissions.", focus: "middle" },
      { title: "Check the latest Vagaro update", detail: "Read the time and status. Open Vagaro sync when you see a warning.", focus: "middle" },
      { title: "Open the setting you need", detail: "Use the cards to manage access, updates or history.", focus: "bottom" },
    ],
    check: ["Your role matches what you expect.", "The latest Vagaro status is healthy or you know what needs attention."],
  },
  {
    id: "admin-access",
    capabilityId: "admin-access",
    area: "Settings",
    title: "Give or remove Admin access",
    questions: ["How do I give someone owner, publisher, viewer, or no admin access?"],
    summary: "Choose the lowest level of access a person needs and remove access when they no longer need it.",
    route: "/admin/dam-users",
    screen: "Settings → Admin access",
    screenshot: "/admin-guide/screenshots/27-admin-access.png",
    screenshotAlt: "The Admin access page explaining Owner, Publisher and Viewer roles.",
    keywords: ["access", "permission", "owner", "publisher", "viewer", "remove"],
    before: ["Confirm the person's identity and why they need access.", "Only an Owner can change Admin access."],
    steps: [
      { title: "Open Admin access", detail: "Select Settings, then Admin access.", focus: "top" },
      { title: "Find the person", detail: "Search carefully and confirm the phone number or email belongs to the intended person.", focus: "middle" },
      { title: "Choose the role", detail: "Use Viewer for read-only access, Publisher for approved content changes and Owner only for full control.", focus: "middle" },
      { title: "Save and confirm", detail: "Save the change. Ask the person to sign in and confirm they see the right tools.", focus: "bottom" },
      { title: "Remove access when it ends", detail: "Choose No admin access when the person no longer needs the Admin panel.", focus: "bottom" },
    ],
    check: ["The correct person has the correct role.", "Nobody has more access than their work requires."],
    warning: "Owner access can change everything in Admin. Give it only to people who need full control.",
  },
  {
    id: "vagaro-sync",
    capabilityId: "vagaro-sync",
    area: "Settings",
    title: "Check or run the Vagaro update",
    questions: ["How do I see whether Vagaro data and booking mappings are healthy?", "How do I run a Vagaro sync now?", "How often does Vagaro sync, what does it update, and when should I run it manually?"],
    summary: "Check when Vagaro last updated LashPop and run it again after an important Vagaro change.",
    route: "/admin/system/syncs",
    screen: "Settings → Vagaro sync",
    screenshot: "/admin-guide/screenshots/24-vagaro-sync.png",
    screenshotAlt: "The Vagaro sync page showing update status, booking checks and the Sync now control.",
    keywords: ["Vagaro", "sync", "update", "booking", "health", "schedule"],
    steps: [
      { title: "Open Vagaro sync", detail: "Select Settings, then Vagaro sync.", focus: "top" },
      { title: "Read the latest status", detail: "Check categories, services, public staff and team-to-service links. A warning tells you which part needs attention.", focus: "middle" },
      { title: "Know when it runs", detail: "LashPop checks Vagaro automatically three times a day: 6am, 2pm and 10pm Pacific time.", focus: "middle" },
      { title: "Run it after an important change", detail: "Use Sync from Vagaro now after you finish a service, price, availability or staff change in Vagaro.", focus: "middle" },
      { title: "Wait for every part to finish", detail: "Do not close the page while the update is running. Read any warning before publishing.", focus: "bottom" },
    ],
    check: ["Every update part says it completed.", "Visible services have a working booking connection.", "New people and services remain hidden until reviewed."],
    warning: "Finish the Vagaro changes before running the update. An incomplete Vagaro setup can bring incomplete details into LashPop.",
  },
  {
    id: "activity-history",
    capabilityId: "activity-history",
    area: "Settings",
    title: "See who changed something",
    questions: ["How do I see who changed something in the admin panel?"],
    summary: "Use Activity history to see what changed, who changed it and when.",
    route: "/admin/system/audit-log",
    screen: "Settings → Activity history",
    screenshot: "/admin-guide/screenshots/25-activity-history.png",
    screenshotAlt: "The Activity history page with dated Admin changes and the person responsible.",
    keywords: ["history", "who", "changed", "when", "activity"],
    steps: [
      { title: "Open Activity history", detail: "Select Settings, then Activity history.", focus: "top" },
      { title: "Find the change", detail: "Use the date, person, page or action to narrow the list.", focus: "middle" },
      { title: "Open the record", detail: "Read what changed before and after the action.", focus: "middle" },
      { title: "Use the right recovery page", detail: "If you need to undo website settings, open Website versions. For other changes, confirm the safest next step before editing.", focus: "bottom" },
    ],
    check: ["You found the correct record.", "You understand what changed before trying to undo it."],
  },
  {
    id: "website-history",
    capabilityId: "website-history",
    area: "Settings",
    title: "Restore an older website version",
    questions: ["How do I find an older saved website version and restore it without erasing history?"],
    summary: "Review an older saved version and restore it as a new version so the full history remains available.",
    route: "/admin/system/website-history",
    screen: "Settings → Website versions",
    screenshot: "/admin-guide/screenshots/26-website-history.png",
    screenshotAlt: "The Website versions page with dates, saved changes and Restore controls.",
    keywords: ["restore", "version", "undo", "history", "website"],
    before: ["Know which website section changed and roughly when.", "Check Activity history first when you are unsure what happened."],
    steps: [
      { title: "Open Website versions", detail: "Select Settings, then Website versions.", focus: "top" },
      { title: "Find the last correct version", detail: "Use the section name, date and person. Open the details before restoring.", focus: "middle" },
      { title: "Compare the saved values", detail: "Make sure the older version contains the exact wording or settings you want.", focus: "middle" },
      { title: "Select Restore", detail: "Read the confirmation, then restore only when you are certain.", focus: "bottom" },
      { title: "Check the website", detail: "Open the affected page on a phone and computer. The restored values are saved as a new version.", focus: "bottom" },
    ],
    check: ["The intended values are live.", "The earlier and restored versions both remain in history."],
    warning: "Restore changes the website. Compare the version carefully and check the public page straight away.",
  },
]

export function findOwnerGuideArticle(id: string | null | undefined): OwnerGuideArticle | undefined {
  return OWNER_GUIDE_ARTICLES.find((article) => article.id === id)
}

export function ownerGuideSearchText(article: OwnerGuideArticle): string {
  return [
    article.title,
    article.area,
    article.summary,
    article.screen,
    ...article.questions,
    ...article.keywords,
    ...(article.before ?? []),
    ...article.steps.flatMap((step) => [step.title, step.detail]),
    ...article.check,
    article.warning ?? "",
  ].join(" ").toLowerCase()
}

export function searchOwnerGuide(query: string, area: OwnerGuideArea | "All" = "All"): OwnerGuideArticle[] {
  const cleanQuery = query.trim().toLowerCase()
  const terms = cleanQuery.split(/\s+/).filter((term) => term.length > 1 && !["a", "an", "the", "to", "or", "and", "in"].includes(term))
  return OWNER_GUIDE_ARTICLES
    .filter((article) => area === "All" || article.area === area)
    .map((article, index) => {
      if (cleanQuery === "") return { article, score: -index }
      const title = article.title.toLowerCase()
      const summary = article.summary.toLowerCase()
      const questions = article.questions.join(" ").toLowerCase()
      const keywords = article.keywords.join(" ").toLowerCase()
      const allCopy = ownerGuideSearchText(article)
      if (!terms.every((term) => allCopy.includes(term))) return { article, score: Number.NEGATIVE_INFINITY }
      let score = 0
      if (title.includes(cleanQuery)) score += 120
      if (keywords.includes(cleanQuery)) score += 100
      if (questions.includes(cleanQuery)) score += 80
      if (summary.includes(cleanQuery)) score += 40
      score += terms.filter((term) => title.includes(term)).length * 12
      score += terms.filter((term) => keywords.includes(term)).length * 8
      return { article, score }
    })
    .filter((result) => Number.isFinite(result.score))
    .sort((a, b) => b.score - a.score)
    .map((result) => result.article)
}
